CREATE TABLE fw_strings (string CHAR);
.import output.rch fw_strings

DELETE FROM fw_strings WHERE SUBSTR(string,1,5) <> 'REACH';

CREATE TABLE rch AS
	SELECT
		CAST(SUBSTR(string,6,5) AS INTEGER) AS RCH
		,CAST(SUBSTR(string,20,4) AS INTEGER) AS MO
		,CAST(SUBSTR(string,24,3) AS INTEGER) AS DA
		,CAST(SUBSTR(string,27,5) AS INTEGER) AS YR
		,CAST(SUBSTR(string,32,13) AS REAL) AS AREA
		,CAST(SUBSTR(string,45,12) AS REAL) AS FLOW_IN
		,CAST(SUBSTR(string,57,12) AS REAL) AS FLOW_OUT
		,CAST(SUBSTR(string,69,12) AS REAL) AS EVAP
		,CAST(SUBSTR(string,81,12) AS REAL) AS TLOSS
		,CAST(SUBSTR(string,93,12) AS REAL) AS SED_IN
		,CAST(SUBSTR(string,105,12) AS REAL) AS SED_OUT
		,CAST(SUBSTR(string,117,12) AS REAL) AS SEDCONC
		,CAST(SUBSTR(string,129,12) AS REAL) AS ORGN_IN
		,CAST(SUBSTR(string,141,12) AS REAL) AS ORGN_OUT
		,CAST(SUBSTR(string,153,12) AS REAL) AS ORGP_IN
		,CAST(SUBSTR(string,165,12) AS REAL) AS ORGP_OUT
		,CAST(SUBSTR(string,177,12) AS REAL) AS NO3_IN
		,CAST(SUBSTR(string,189,12) AS REAL) AS NO3_OUT
		,CAST(SUBSTR(string,201,12) AS REAL) AS NH4_IN
		,CAST(SUBSTR(string,213,12) AS REAL) AS NH4_OUT
		,CAST(SUBSTR(string,225,12) AS REAL) AS NO2_IN
		,CAST(SUBSTR(string,237,12) AS REAL) AS NO2_OUT
		,CAST(SUBSTR(string,249,12) AS REAL) AS MINP_IN
		,CAST(SUBSTR(string,261,12) AS REAL) AS MINP_OUT
		,CAST(SUBSTR(string,273,12) AS REAL) AS CHLA_IN
		,CAST(SUBSTR(string,285,12) AS REAL) AS CHLA_OUT
		,CAST(SUBSTR(string,297,12) AS REAL) AS CBOD_IN
		,CAST(SUBSTR(string,309,12) AS REAL) AS CBOD_OUT
		,CAST(SUBSTR(string,321,12) AS REAL) AS DISOX_IN
		,CAST(SUBSTR(string,333,12) AS REAL) AS DISOX_OUT
		,CAST(SUBSTR(string,345,12) AS REAL) AS SOLPST_IN
		,CAST(SUBSTR(string,357,12) AS REAL) AS SOLPST_OUT
		,CAST(SUBSTR(string,369,12) AS REAL) AS SORPST_IN
		,CAST(SUBSTR(string,381,12) AS REAL) AS SORPST_OUT
		,CAST(SUBSTR(string,393,12) AS REAL) AS REACTPST
		,CAST(SUBSTR(string,405,12) AS REAL) AS VOLPST
		,CAST(SUBSTR(string,417,12) AS REAL) AS SETTLPST
		,CAST(SUBSTR(string,429,12) AS REAL) AS RESUSP_PST
		,CAST(SUBSTR(string,441,12) AS REAL) AS DIFFUSEPST
		,CAST(SUBSTR(string,453,12) AS REAL) AS REACBEDPST
		,CAST(SUBSTR(string,465,12) AS REAL) AS BURYPST
		,CAST(SUBSTR(string,477,12) AS REAL) AS BED_PST
		,CAST(SUBSTR(string,489,12) AS REAL) AS BACTP_OUT
		,CAST(SUBSTR(string,501,12) AS REAL) AS BACTLP_OUT
		,CAST(SUBSTR(string,513,12) AS REAL) AS CMETAL_1
		,CAST(SUBSTR(string,525,12) AS REAL) AS CMETAL_2
		,CAST(SUBSTR(string,537,12) AS REAL) AS CMETAL_3
		,CAST(SUBSTR(string,549,12) AS REAL) AS TOT_N
		,CAST(SUBSTR(string,561,12) AS REAL) AS TOT_P
		,CAST(SUBSTR(string,573,12) AS REAL) AS NO3CONC
		,CAST(SUBSTR(string,585,12) AS REAL) AS WTMP
	FROM fw_strings;

DROP TABLE fw_strings;

CREATE TABLE fw_strings (string CHAR);
.import output.hru fw_strings

DELETE FROM fw_strings WHERE SUBSTR(string,1,4) NOT IN
	('WATR','BERM','FRSD','FRSE','FRST','FESC','WETN','SOYB','CORN','CSIL','ALFA','POTA','SCRN','GRBN');

CREATE TABLE hru AS
	SELECT
		CAST(SUBSTR(string,1,4) AS TEXT) AS LULC
		,CAST(SUBSTR(string,5,5) AS INTEGER) AS HRU
		,CAST(SUBSTR(string,11,9) AS TEXT) AS GIS
		,CAST(SUBSTR(string,20,9) AS INTEGER) AS SUB
		,CAST(SUBSTR(string,30,4) AS INTEGER) AS MO
		,CAST(SUBSTR(string,33,3) AS INTEGER) AS DA
		,CAST(SUBSTR(string,36,5) AS INTEGER) AS YR
		,CAST(SUBSTR(string,41,11) AS REAL) AS AREA
		,CAST(SUBSTR(string,52,10) AS REAL) AS PRECIP
		,CAST(SUBSTR(string,62,10) AS REAL) AS SNOFALL
		,CAST(SUBSTR(string,72,10) AS REAL) AS SNOMELT
		,CAST(SUBSTR(string,82,10) AS REAL) AS IRR
		,CAST(SUBSTR(string,92,10) AS REAL) AS PET
		,CAST(SUBSTR(string,102,10) AS REAL) AS ET
		,CAST(SUBSTR(string,112,10) AS REAL) AS SW_INIT
		,CAST(SUBSTR(string,122,10) AS REAL) AS SW_END
		,CAST(SUBSTR(string,132,10) AS REAL) AS PERC
		,CAST(SUBSTR(string,142,10) AS REAL) AS GW_RCHG
		,CAST(SUBSTR(string,152,10) AS REAL) AS DA_RCHG
		,CAST(SUBSTR(string,162,10) AS REAL) AS REVAP
		,CAST(SUBSTR(string,172,10) AS REAL) AS SA_IRR
		,CAST(SUBSTR(string,182,10) AS REAL) AS DA_IRR
		,CAST(SUBSTR(string,192,10) AS REAL) AS SA_ST
		,CAST(SUBSTR(string,202,10) AS REAL) AS DA_ST
		,CAST(SUBSTR(string,212,10) AS REAL) AS SURQ_GEN
		,CAST(SUBSTR(string,222,10) AS REAL) AS SURQ_CNT
		,CAST(SUBSTR(string,232,10) AS REAL) AS TLOSS
		,CAST(SUBSTR(string,242,10) AS REAL) AS LATQ
		,CAST(SUBSTR(string,252,10) AS REAL) AS GW_Q
		,CAST(SUBSTR(string,262,10) AS REAL) AS WYLD
		,CAST(SUBSTR(string,272,10) AS REAL) AS DAILYCN
		,CAST(SUBSTR(string,282,10) AS REAL) AS TMP_AV
		,CAST(SUBSTR(string,292,10) AS REAL) AS TMP_MX
		,CAST(SUBSTR(string,302,10) AS REAL) AS TMP_MN
		,CAST(SUBSTR(string,312,10) AS REAL) AS SOL_TMP
		,CAST(SUBSTR(string,322,10) AS REAL) AS SOLAR
		,CAST(SUBSTR(string,332,10) AS REAL) AS SYLD
		,CAST(SUBSTR(string,342,10) AS REAL) AS USLE
		,CAST(SUBSTR(string,352,10) AS REAL) AS N_APP
		,CAST(SUBSTR(string,362,10) AS REAL) AS P_APP
		,CAST(SUBSTR(string,372,10) AS REAL) AS NAUTO
		,CAST(SUBSTR(string,382,10) AS REAL) AS PAUTO
		,CAST(SUBSTR(string,392,10) AS REAL) AS NGRZ
		,CAST(SUBSTR(string,402,10) AS REAL) AS PGRZ
		,CAST(SUBSTR(string,412,10) AS REAL) AS CFERTN
		,CAST(SUBSTR(string,422,10) AS REAL) AS CFERTP
		,CAST(SUBSTR(string,432,10) AS REAL) AS NRAIN
		,CAST(SUBSTR(string,442,10) AS REAL) AS NFIX
		,CAST(SUBSTR(string,452,10) AS REAL) AS F_MN
		,CAST(SUBSTR(string,462,10) AS REAL) AS A_MN
		,CAST(SUBSTR(string,472,10) AS REAL) AS A_SN
		,CAST(SUBSTR(string,482,10) AS REAL) AS F_MP
		,CAST(SUBSTR(string,492,10) AS REAL) AS AO_LP
		,CAST(SUBSTR(string,502,10) AS REAL) AS L_AP
		,CAST(SUBSTR(string,512,10) AS REAL) AS A_SP
		,CAST(SUBSTR(string,522,10) AS REAL) AS DNIT
		,CAST(SUBSTR(string,532,10) AS REAL) AS NUP
		,CAST(SUBSTR(string,542,10) AS REAL) AS PUP
		,CAST(SUBSTR(string,552,10) AS REAL) AS ORGN
		,CAST(SUBSTR(string,562,10) AS REAL) AS ORGP
		,CAST(SUBSTR(string,572,10) AS REAL) AS SEDP
		,CAST(SUBSTR(string,582,10) AS REAL) AS NSURQ
		,CAST(SUBSTR(string,592,10) AS REAL) AS NLATQ
		,CAST(SUBSTR(string,602,10) AS REAL) AS NO3L
		,CAST(SUBSTR(string,612,10) AS REAL) AS NO3GW
		,CAST(SUBSTR(string,622,10) AS REAL) AS SOLP
		,CAST(SUBSTR(string,632,10) AS REAL) AS P_GW
		,CAST(SUBSTR(string,642,10) AS REAL) AS W_STRS
		,CAST(SUBSTR(string,652,10) AS REAL) AS TMP_STRS
		,CAST(SUBSTR(string,662,10) AS REAL) AS N_STRS
		,CAST(SUBSTR(string,672,10) AS REAL) AS P_STRS
		,CAST(SUBSTR(string,682,10) AS REAL) AS BIOM
		,CAST(SUBSTR(string,692,10) AS REAL) AS LAI
		,CAST(SUBSTR(string,702,10) AS REAL) AS YLD
		,CAST(SUBSTR(string,712,11) AS REAL) AS BACTP
		,CAST(SUBSTR(string,723,11) AS REAL) AS BACTLP
		,CAST(SUBSTR(string,734,11) AS REAL) AS WTAB
		,CAST(SUBSTR(string,744,10) AS REAL) AS WTABELO
		,CAST(SUBSTR(string,754,10) AS REAL) AS SNO_HRU
		,CAST(SUBSTR(string,764,10) AS REAL) AS CMUP_KGH
		,CAST(SUBSTR(string,774,10) AS REAL) AS CMTOT_KGH
		,CAST(SUBSTR(string,784,10) AS REAL) AS QTILE
		,CAST(SUBSTR(string,794,10) AS REAL) AS TNO3
		,CAST(SUBSTR(string,804,10) AS REAL) AS LNO3
		,CAST(SUBSTR(string,814,10) AS REAL) AS GW_Q_D
		,CAST(SUBSTR(string,824,10) AS REAL) AS LATQ_CNT
	FROM fw_strings;

DROP TABLE fw_strings;

CREATE TABLE fw_strings (string CHAR);
.import output.sub fw_strings

DELETE FROM fw_strings WHERE SUBSTR(string,1,6) <> 'BIGSUB';

CREATE TABLE sub AS
	SELECT
		CAST(SUBSTR(string,7,4) AS INTEGER) AS SUB
		,CAST(SUBSTR(string,20,3) AS INTEGER) AS MO
		,CAST(SUBSTR(string,23,3) AS INTEGER) AS DA
		,CAST(SUBSTR(string,26,5) AS INTEGER) AS YR
		,CAST(SUBSTR(string,31,10) AS REAL) AS AREA
		,CAST(SUBSTR(string,42,10) AS REAL) AS PRECIP
		,CAST(SUBSTR(string,45,10) AS REAL) AS SNOMELT
		,CAST(SUBSTR(string,52,10) AS REAL) AS PET
		,CAST(SUBSTR(string,72,10) AS REAL) AS ET
		,CAST(SUBSTR(string,82,10) AS REAL) AS SW
		,CAST(SUBSTR(string,92,10) AS REAL) AS PERC
		,CAST(SUBSTR(string,102,10) AS REAL) AS SURQ
		,CAST(SUBSTR(string,112,10) AS REAL) AS GW_Q
		,CAST(SUBSTR(string,122,10) AS REAL) AS WYLD
		,CAST(SUBSTR(string,132,10) AS REAL) AS SYLD
		,CAST(SUBSTR(string,142,10) AS REAL) AS ORGN
		,CAST(SUBSTR(string,152,10) AS REAL) AS ORGP
		,CAST(SUBSTR(string,162,10) AS REAL) AS NSURQ
		,CAST(SUBSTR(string,172,10) AS REAL) AS SOLP
		,CAST(SUBSTR(string,182,10) AS REAL) AS SEDP
		,CAST(SUBSTR(string,192,10) AS REAL) AS LATQ
		,CAST(SUBSTR(string,202,10) AS REAL) AS LATNO3
		,CAST(SUBSTR(string,212,10) AS REAL) AS GWNO3
		,CAST(SUBSTR(string,222,11) AS REAL) AS CHOLA
		,CAST(SUBSTR(string,233,10) AS REAL) AS CBODU
		,CAST(SUBSTR(string,243,10) AS REAL) AS DOXQ
		,CAST(SUBSTR(string,253,10) AS REAL) AS TNO3
	FROM fw_strings;

DROP TABLE fw_strings;

VACUUM;